### ISSUE TITLE
Blank Screen on mac 10.12

### ISSUE THREAD

**Issue by hndr91** [pearsonlab/pygonogo#5]
I have tried in mac 10.12, standalone PsychoPy2 v.1.84.2 and I got blank screen. The output log said it cannot import plexon library. Here's the full log,

> 2017-03-01 02:45:06,400 (8266) WARNING: Cannot import Plexon dynamic library in your system.
> 2017-03-01 02:45:06,400 (8266) WARNING: Could not find PlexClient.dll in your system.
> {'Task Name': 'gonogo', 'Subject': 'test'}
> 17.0979 	WARNING 	Requested an unavailable screen number - using first available.
> 17.0985 	WARNING 	User requested fullscreen with size [800 600], but screen is actually [1280, 800]. Using actual size
> /Users/<uname>/data/gonogo/test
> 2017-03-01 02:45:17,856 (8266) WARNING: Failed to load Plexon client library.
> Traceback (most recent call last):
>   File "/Users/<uname>/Documents/Course/EEG/Project-EEG/pygonogo/gonogo.py", line 8, in <module>
>     mytask = task.Task()
>   File "/Users/<uname>/Documents/Course/EEG/Project-EEG/pygonogo/task.py", line 21, in __init__
>     self.setup()
>   File "/Users/<uname>/Documents/Course/EEG/Project-EEG/pygonogo/task.py", line 41, in setup
>     self.taskname, self.subject)
>   File "/Users/<uname>/Documents/Course/EEG/Project-EEG/pygonogo/initializers.py", line 92, in setup_data_file
>     os.makedirs(datadir)
>   File "os.pyc", line 150, in makedirs
>   File "os.pyc", line 157, in makedirs
> OSError: [Errno 20] Not a directory: '/Users/<uname>/data/gonogo'

**Comment by jmxpearson** [comment]
Are you interested in using the Plexon functionality?

**Comment by hndr91** [comment]
I'm sorry sir, I still didn't understand what the plexon library for @jmxpearson

**Comment by jmxpearson** [comment]
Should be fixed now.

**Comment by hndr91** [comment]
thanks sir, everything is fine now @jmxpearson 
but, I got this error when I have file called "data" (not even a directory) in my home directory

> /Users/user/data/gonogo/test
> Traceback (most recent call last):
>   File "/Users/user/Documents/Course/EEG/Project-EEG/pygonogo/gonogo.py", line 8, in <module>
>     mytask = task.Task()
>   File "/Users/user/Documents/Course/EEG/Project-EEG/pygonogo/task.py", line 26, in __init__
>     self.setup()
>   File "/Users/user/Documents/Course/EEG/Project-EEG/pygonogo/task.py", line 51, in setup
>     self.taskname, self.subject)
>   File "/Users/user/Documents/Course/EEG/Project-EEG/pygonogo/initializers.py", line 98, in setup_data_file
>     os.makedirs(datadir)
>   File "os.pyc", line 150, in makedirs
>   File "os.pyc", line 157, in makedirs
> OSError: [Errno 20] Not a directory: '/Users/user/data/gonogo'

It is easy to fix, but I think the code should be check the file too,

**Comment by jmxpearson** [comment]
I think it's fine to make the check, but if the user already has a file `~/data`, then we would need to allow users to specify an alternate directory. This is not a hard fix, but it would require changing a few things.

I don't have time to do this at the moment, but I'm happy to review a pull request to that effect.
